# definition of all Ble Connected for Bluetooth tags
#
# Main command definition for tags version 1.0.0 and lower
COMMAND_DATA_LOGGER_GET = "L"
COMMAND_DATA_LOGGER_RESET = "RST"
COMMAND_LED_ON = "LED_ON"
COMMAND_LED_OFF = "LED_OFF"
COMMAND_BUZZED_ON = "BUZZ_ON"
COMMAND_BUZZED_OFF = "BUZZ_OFF"
#
# additionnal 2.0.0
COMMAND_TOR_ON_UART_CMD = "TOR_ON"
COMMAND_TOR_OFF_UART_CMD = "TOR_OFF"
COMMAND_RAZ_COUNT_UART_CMD = "RAZ_COUNT"
COMMAND_REBOOT_UART_CMD = "REBOOT"
COMMAND_TAG_DIAG_HW_CMD = "DIAG_HW"
COMMAND_TAG_DIAG_FORMATS_CMD = "DIAG_FORMATS"
COMMAND_TAG_DIAG_SERIAL_CMD = "DIAG_SERIAL"
COMMAND_TAG_DIAG_HW_ID_CMD = "HW_VERS"
COMMAND_TAG_DIAG_FW_ID_CMD = "FW_VERS"
COMMAND_VOLTAGE_CMD = "VOLT"
# 
COMMAND_LOG_UART_STR = "LOG_DL"
COMMAND_RST_LOG_UART_STR = "LOG_RST"
COMMAND_TOR_ON_UART_STR = "DIGI_ON"
COMMAND_TOR_OFF_UART_STR = "DIGI_OFF"
COMMAND_NFC_RELASE_PWD_STR = "NFC_RELEASE_PWD"
COMMAND_TAG_DIAG_DATE_STR = "DIAG_PROD_DATE"
COMMAND_VOLTAGE_STR = "GET_BATT_VOLTAGE"
COMMAND_TAG_REBOOT_STR = "TAG_REBOOT"
#
# update 2.1.0 data logger
READ_CALIB_COEF_STR = "READ_CALIB_COEF"
SET_CALIB_COEF_STR = "SET_CALIB_3_COEF"
SET_CALIB_COEF_A_STR = "SET_CALIB_COEF_A"
SET_CALIB_COEF_B_STR = "SET_CALIB_COEF_B"
SET_CALIB_COEF_C_STR = "SET_CALIB_COEF_C"
DATALOGGER_START_STR = "DATALOGGER_START"
READ_DATA_STR = "READ_DATA"
DATALOGGER_STOP_STR = "DATALOGGER_STOP"
READ_START_DATE_STR = "READ_START_DATE"
SET_CALIB_EN_STR = "SET_CALIB_EN"
READ_CALIB_EN_STR = "READ_CALIB_EN"
READ_REPORT_VAL_STR = "READ_REPORT_VAL"
READ_REPORT_RES_STR = "READ_REPORT_RES"
#
NFC_DISABLE_TAG_STR = "NFC_DISABLE_TAG"
#
# update 3.0.0 dfu commands
TAG_DFU_VERSION = "TAG_DFU_VERSION"
TAG_DFU_CODE_SIZE = "TAG_DFU_CODE_SIZE"
TAG_DFU_MODE_ON = "TAG_DFU_MODE_ON"
#
# known answer and return keys
KEY_DATA_LOGGER_START_DOWNLOAD = "DATA_START"
KEY_DATA_LOGGER_END_DOWNLOAD = "END_OF_DATA"
KEY_DATA_LOGGER_EXPECTED_DATA = "Nb data to get"
KEY_DATA_LOGGER_FORMAT_DATA_TEMP = "Temperature LOG"
KEY_DATA_LOGGER_FORMAT_DATA_RHT = "Temperature and Humidity LOG"
KEY_DATA_LOGGER_FORMAT_DATA_MOV = "Motion Sensor LOG"
KEY_DATA_LOGGER_FORMAT_DATA_MAG = "Magnet Sensor LOG"
KEY_DATA_LOGGER_FORMAT_DATA_ANG = "Acceleration Sensor LOG"
#
# key for en 12830
KEY_EN_DOWNLOAD_START = "---DOWNLOAD_START---"
KEY_EN_FIRM_VERSION = "Firmware version"
KEY_EN_MAC_ADDRESS = "MacAddress"
KEY_EN_NAME = "Name"
KEY_EN_UNIT = "Unit"
KEY_EN_START_DATE = "Start date"
KEY_EN_DATA_START = "<DATA_START>"
KEY_EN_DATA_END = "<DATA_END>"
KEY_EN_DATA_CRC = "CRC16"
KEY_EN_DOWNLOAD_END = "---DOWNLOAD_END---"
KEY_EN_DL_NOT_STARTED = "READ_DATA: LOG not started!"